name: Deployment Workflow
on:
  push:
    branches:
      - master
      
  
jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: preparation
        run: echo "Preparing to deploy ..."
    
      - name: checks out the repository
        uses: actions/checkout@v4

      - name: "Logs into docker"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Build our code"
        env:
          IMAGE_NAME: simplepersonal1000
          VERSION: 1
          USERNAME: masturrh
        run: |
            sudo docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
            sudo docker push $USERNAME/$IMAGE_NAME:$VERSION

          

    